// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmscmlzivpbqcnoswihq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtc2NtbHppdnBicWNub3N3aWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDE5NzAsImV4cCI6MjA3MzUxNzk3MH0.Md0ITjsuBF6tTi-SrvOEeKpMGFg_TNu0HWn2ozSV1-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});